import '@/styles/globals.css';
import { ThemeProvider } from '@mui/material';
import { Noto_Sans_JP } from 'next/font/google';
import Head from 'next/head';
import CustomDivider from '@/components/CustomDivider';
import Header from '@/components/Header';
import theme from '@/theme/index';

const notoSansJp = Noto_Sans_JP({ weight: '700', subsets: ['latin'] });

export default function App({ Component, pageProps }) {
    return (
        <ThemeProvider theme={theme}>
            <style jsx global>{`
                html {
                    font-family: ${notoSansJp};
                }
            `}</style>
            <Head>
                <title>nemogLog</title>
                <meta name='description' content='Generated by create next app' />
                <meta name='viewport' content='width=device-width, initial-scale=1' />
                <link rel='icon' href='/favicon.ico' />
            </Head>
            <Header />
            <CustomDivider />
            <Component {...pageProps} />
        </ThemeProvider>
    );
}
