import { Box, Divider, Typography } from '@mui/material';
import { Inter } from 'next/font/google';
import Head from 'next/head';
import Link from 'next/link';
import Profile from '../components/Profile';
import Post from '../interfaces/post';
import { getAllPosts } from '../lib/api';
import styles from '../styles/Home.module.css';

const inter = Inter({ subsets: ['latin'] });

type Props = {
    allPosts: Post[];
};

export default function Home({ allPosts }: Props) {
    return (
        <>
            <Head>
                <title>nemogLog</title>
                <meta name='description' content='Generated by create next app' />
                <meta name='viewport' content='width=device-width, initial-scale=1' />
                <link rel='icon' href='/favicon.ico' />
            </Head>
            <Box
                sx={{
                    px: 2,
                }}
            >
                <Divider
                    sx={{
                        borderColor: 'primary.main',
                        borderBottomWidth: 2,
                        mx: 4,
                        maxWidth: '48rem',
                        m: 'auto',
                    }}
                />
            </Box>
            <Profile />
            <Box
                sx={{
                    px: 2,
                }}
            >
                <Divider
                    sx={{
                        borderColor: 'primary.main',
                        borderBottomWidth: 2,
                        mx: 4,
                        maxWidth: '48rem',
                        m: 'auto',
                    }}
                />
            </Box>
            <main className={styles.main}>
                <Typography variant='h5'>Posts</Typography>
                {allPosts.map(({ title, date, slug }) => {
                    return (
                        <Box sx={{ py: 2 }} key={slug}>
                            <Link href={{ pathname: '/[slug]', query: { slug: slug } }}>
                                <Typography
                                    variant='h6'
                                    sx={{
                                        color: 'primary.main',
                                    }}
                                >
                                    {title}
                                </Typography>
                                <Typography sx={{ p: 0 }}>{date}</Typography>
                            </Link>
                        </Box>
                    );
                })}
            </main>
        </>
    );
}

export const getStaticProps = async () => {
    const allPosts = getAllPosts(['title', 'date', 'slug', 'coverImage', 'except']);

    return {
        props: { allPosts },
    };
};
