import Head from 'next/head';
import Post from '../interfaces/post';
import Image from 'next/image';
import { Inter } from 'next/font/google';
import styles from '@/styles/Home.module.css';
import { getAllPosts } from '../lib/api';
import Link from 'next/link';
import { Box, Typography } from '@mui/material';
import YouTube, { YouTubeProps } from 'react-youtube';

const inter = Inter({ subsets: ['latin'] });

type Props = {
  allPosts: Post[];
};

export default function Home({ allPosts }: Props) {
  return (
    <>
      <Head>
        <title>nemogLog</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        {allPosts.map(({ title, date, slug }) => {
          return (
            <Box sx={{ py: 2 }} key={slug}>
              <Link href={{ pathname: '/[slug]', query: { slug: slug } }}>
                <Typography variant="h6">{title}</Typography>
                <Typography sx={{ p: 0 }}>{date}</Typography>
              </Link>
            </Box>
          );
        })}
      </main>
    </>
  );
}

export const getStaticProps = async () => {
  const allPosts = getAllPosts([
    'title',
    'date',
    'slug',
    'coverImage',
    'except',
  ]);

  return {
    props: { allPosts },
  };
};
